export default {
  SPLASH_SCREEN: 'Splash',
  LOG_IN: 'Log in',
  LOGOUT: 'Log out',
  REGISTER: 'Register',
  OTP: 'OTP Screen',
  HOME: 'Home',
  HOME_SCREEN: 'Home Screen',
  PROFILE: 'Profile',
  LOGIN: 'Login',
  SETTINGS: 'Settings',
  TABS: 'Tabs',
  ACCOUNT: 'Account',
  TRIPS: 'My Trips',
  // MYLOADS: 'My Loads',
  BOOKING: 'Booking',
  DASHBOARD: 'Dashboard',
  CREATE_LOADS: 'Create Loads',
  NOTIFICATION_SCREEN: 'Notification',
  HELP_SCREEN: 'Help',
  TRACKING_SCREEN: 'Vehicle Location',
  TEST_SCREEN: 'test',
  // PICK_LOCATION_SCREEN: 'Pick Location',
  CONTACT_US_SCREEN: 'Contact us',
  REFER_APP_SCREEN: 'Share app',
  TERMS_AND_CONDITIONS_SCREEN: 'TnC & Privacy Policy',
  PRIVACY_POLICY: 'Privacy Policy',
  // single details page -------------------------------------------
  PENDING_TRIPS_DETAILS: 'Pending Trips Details',
  COMPLETE_TRIPS_DETAILS: 'Completed Trips Details',
  CONFIRMED_TRIPS_DETAILS: 'Confirmed Trips Details',
  DRIVER_TRIPS_DETAILS: 'Driver Trips Details',
  DOC_VIEWER: 'Document Viewer',

  // new ------------------------------------------------------------
  LOAD_DETAILS: 'Load Details',
  VEHICLES: 'My Vehicles',
  ADD_VEHICLE: 'Add Vehicle',
  VEHICLE_DETAILS: 'Vehicle Details',
  DRIVERS: 'My Drivers',
  DRIVER_DETAILS: 'Driver Details',
  ADD_DRIVER: 'Add Driver',
  ADD_DRIVER_2: 'Add Driver 2',
  ADD_DRIVER_3: 'Add Driver 3',
  SEARCH_LOAD: 'Search Loads',
  QUOTATIONS: 'Pending',
  CONFIRMED: 'Confirmed',
  COMPLETED: 'Completed',
  DRIVER_TRIPS: 'Driver Trips',
  DOCUMENT_VIEWER: 'Document Viewer',
};
